# Generated by Django 5.1 on 2024-09-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=50)),
                ('recipeDesc', models.TextField()),
                ('recipeImage', models.ImageField(upload_to='recipeImages')),
            ],
        ),
    ]
